[workspace]
channels = ["conda-forge"]
name = "P2026"
platforms = ["osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
monitor = "python py_files/monitor.py"
install-frontend = "npm install"

[tasks.frontend]
cmd = "npm run dev"
depends-on = ["install-frontend"]

[tasks.fullstack]
cmd = "python start_all.py"
depends-on = ["install-frontend"]

[tasks.build]
cmd = "npm run build"
depends-on = ["install-frontend"]

[tasks.prod]
cmd = "python start_prod.py"
depends-on = ["build"]

[dependencies]
python = ">=3.14.6,<3.15"
pyserial = ">=3.5,<4"
websockets = ">=16.0,<17"
prompt_toolkit = ">=3.0.52,<4"
nodejs = ">=26.5.0,<26.6"
caddy = ">=2.11.4,<3"
numpy = ">=2.5.1,<3"
scipy = ">=1.18.0,<2"
paho-mqtt = ">=2.1.0,<3"
